routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Auth::routes();

/**==========================Language Change Routes ================================*/

Route::get('setlang/{lang}', function($lang)
{
    session()->put('locale', $lang);

    app()->setLocale($lang);
    return  redirect()->back();
})->name('setlang');

Route::get('/home', 'HomeController@index')->name('home');

/*--------------------------Frontend Routes ---------------------------------*/
Route::get('/', function () {
    return view('frontend.pages.home');
});

Route::get('contact_us' , 'HomeController@contactUs')->name('contactUs');
Route::post('contact_us' , 'HomeController@postContactUs')->name('postContactUs');


/*-------------------------- End Frontend Routes ---------------------------------*/


/*--------------------------Admin Routes ---------------------------------*/
Route::get('/', function () {
    return view('frontend.pages.home');
});



/*-------------------------- End Admin Routes ---------------------------------*/

Route::group(['namespace' => 'Admin' , 'prefix' => 'admin'] , function(){
    Route::get('/login' , 'AdminController@login')->name('admin.login');
    Route::post('/login' , 'AdminController@postLogin')->name('admin.postLogin');
    Route::group(['middleware' => 'admin'], function() {
        Route::get('/', 'AdminController@dashboard')->name("admin.dashboard");


        Route::resources([
            'adminContacts' => 'ContactsController',
            'adminCategories' => 'CategoriesController',
            'products' => 'ProductsController',
        ]);
    });
});

app/Models/Contact.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    protected  $fillable =
        [
            'contact_name',
            'contact_email',
            'contact_phone',
            'contact_message'
        ];
}

app/Http/Controllers/Admin/ContactsController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Contact;
class ContactsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $contacts =  Contact::all();

        return view('admin.contacts.index' , compact('contacts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
       $contact =  Contact::find($id);

       return view('admin.contacts.show' , compact('contact'));
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/contacts/index.blade.php
@extends('admin.layouts.layout')

@section('styles')
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.16/b-1.5.1/r-2.2.1/datatables.min.css"/>
    <link rel="stylesheet" href="{{ asset('css/toastr.css') }}">
@endsection

@section('content')
    <div class="app-content content">
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-12  col-12 mb-2">
                    <h3 class="content-header-title mb-0">Contacts Massages List</h3>
                    <div class="row breadcrumbs-top">
                        <div class="breadcrumb-wrapper col-12">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{{route("admin.dashboard")}}">Home</a>
                                </li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-body">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <a class="heading-elements-toggle"><i class="fa fa-ellipsis-v font-medium-3"></i></a>
                                <div class="heading-elements">
                                    <ul class="list-inline mb-0">
                                        <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                        <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="card-content collapse show">
                                <div class="card-body">
                                    <table class="table " id="datas">
                                            <thead>
                                                <tr>
                                                    <th>Name</th>
                                                    <th>Email</th>
                                                    <th>Phone</th>
                                                    <th>View</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @if($contacts->first())
                                                    @foreach($contacts as $contact)
                                                        <tr>
                                                            <td> {{ $contact->contact_name	 }} </td>
                                                            <td> {{ $contact->contact_email	 }} </td>
                                                            <td> {{ $contact->contact_phone	 }} </td>
                                                            <td>
                                                                <a href="{{ route('adminContacts.show' , ['id' => $contact->id]) }}">
                                                                    <i class="fa fa-eye-slash"></i>
                                                                </a>
                                                            </td>
                                                        </tr>
                                                    @endforeach
                                                @endif
                                            </tbody>
                                        </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <!--data Tables -->
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.16/b-1.5.1/r-2.2.1/datatables.min.js"></script>
    <!-- / data Tables -->
    <script>
        $('#datas').DataTable({
            responsive: true,
            order: [[ 0, 'desc' ], [ 1, 'desc' ]]
        });
    </script>
    <!-- Toastr js -->
    <script src="{{ asset('/js/toastr.min.js') }}"></script>
    <script>
        @if(Session::has('success'))
        toastr.success('{{ Session::get('success') }}', {"showMethod": "fadeIn", "hideMethod": "fadeOut", timeOut: 2000});
        @endif
    </script>
    <!--  /Toastr js -->
@endsection

resources/views/admin/contacts/show.blade.php
@extends('admin.layouts.layout')



@section('content')
    <div class="app-content content">
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-12  col-12 mb-2">
                    <h3 class="content-header-title mb-0">Contacts Massage</h3>
                    <div class="row breadcrumbs-top">
                        <div class="breadcrumb-wrapper col-12">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{{route("admin.dashboard")}}">Home</a>
                                </li>
                                <li class="breadcrumb-item">
                                    <a href="{{route("adminContacts.index")}}">Contacts List</a>
                                </li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-body">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <a class="heading-elements-toggle"><i class="fa fa-ellipsis-v font-medium-3"></i></a>
                                <div class="heading-elements">
                                    <ul class="list-inline mb-0">
                                        <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                        <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="card-content collapse show">
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col-md-12 col-sm-12 text-center text-md-left">
                                            <p class="lead">Contact Information</p>
                                            <div class="row">
                                                <div class="col-md-8">
                                                    <table class="table table-borderless table-sm">
                                                        <tbody>
                                                        <tr>
                                                            <td>Name</td>
                                                            <td class="text-right">{{ $contact->contact_name }}</td>
                                                        </tr>
                                                        <tr>
                                                            <td>Email</td>
                                                            <td class="text-right">{{ $contact->contact_email }}</td>
                                                        </tr>
                                                        <tr>
                                                            <td>Phone</td>
                                                            <td class="text-right">{{ $contact->contact_phone }}</td>
                                                        </tr>
                                                        <tr>
                                                            <td>Message</td>
                                                            <td class="text-right">{{ $contact->contact_message }}</td>
                                                        </tr>
                                                        </tbody>
                                                    </table>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection